var annotated_dup =
[
    [ "Channel", "classChannel.html", "classChannel" ],
    [ "Client", "classClient.html", "classClient" ],
    [ "Command", "classCommand.html", "classCommand" ],
    [ "Help", "classHelp.html", "classHelp" ],
    [ "Invite", "classInvite.html", "classInvite" ],
    [ "Join", "classJoin.html", "classJoin" ],
    [ "Kick", "classKick.html", "classKick" ],
    [ "List", "classList.html", "classList" ],
    [ "Message", "classMessage.html", "classMessage" ],
    [ "Mode", "classMode.html", "classMode" ],
    [ "Names", "classNames.html", "classNames" ],
    [ "Nick", "classNick.html", "classNick" ],
    [ "Notice", "classNotice.html", "classNotice" ],
    [ "Part", "classPart.html", "classPart" ],
    [ "Pass", "classPass.html", "classPass" ],
    [ "Ping", "classPing.html", "classPing" ],
    [ "PrivMsg", "classPrivMsg.html", "classPrivMsg" ],
    [ "Quit", "classQuit.html", "classQuit" ],
    [ "Server", "classServer.html", "classServer" ],
    [ "Topic", "classTopic.html", "classTopic" ],
    [ "User", "classUser.html", "classUser" ],
    [ "Whois", "classWhois.html", "classWhois" ]
];