var annotated_dup =
[
    [ "BanMask", "classBanMask.html", "classBanMask" ],
    [ "CantSentMessagesOutside", "classCantSentMessagesOutside.html", "classCantSentMessagesOutside" ],
    [ "Channel", "classChannel.html", "classChannel" ],
    [ "ChannelModeType", "classChannelModeType.html", "classChannelModeType" ],
    [ "Client", "classClient.html", "classClient" ],
    [ "Command", "classCommand.html", "classCommand" ],
    [ "Help", "classHelp.html", "classHelp" ],
    [ "Invite", "classInvite.html", "classInvite" ],
    [ "InviteOnly", "classInviteOnly.html", "classInviteOnly" ],
    [ "Join", "classJoin.html", "classJoin" ],
    [ "Key", "classKey.html", "classKey" ],
    [ "Kick", "classKick.html", "classKick" ],
    [ "List", "classList.html", "classList" ],
    [ "Message", "classMessage.html", "classMessage" ],
    [ "Mode", "classMode.html", "classMode" ],
    [ "Moderated", "classModerated.html", "classModerated" ],
    [ "Names", "classNames.html", "classNames" ],
    [ "Nick", "classNick.html", "classNick" ],
    [ "Notice", "classNotice.html", "classNotice" ],
    [ "Operator", "classOperator.html", "classOperator" ],
    [ "Part", "classPart.html", "classPart" ],
    [ "Pass", "classPass.html", "classPass" ],
    [ "Ping", "classPing.html", "classPing" ],
    [ "PrivMsg", "classPrivMsg.html", "classPrivMsg" ],
    [ "Quit", "classQuit.html", "classQuit" ],
    [ "Secret", "classSecret.html", "classSecret" ],
    [ "Server", "classServer.html", "classServer" ],
    [ "Topic", "classTopic.html", "classTopic" ],
    [ "TopicSettableByChannelOperatorOnly", "classTopicSettableByChannelOperatorOnly.html", "classTopicSettableByChannelOperatorOnly" ],
    [ "User", "classUser.html", "classUser" ],
    [ "UserLimit", "classUserLimit.html", "classUserLimit" ],
    [ "Whois", "classWhois.html", "classWhois" ]
];