var annotated_dup =
[
    [ "Away", "classAway.html", "classAway" ],
    [ "Ban", "classBan.html", "classBan" ],
    [ "Channel", "classChannel.html", "classChannel" ],
    [ "Client", "classClient.html", "classClient" ],
    [ "Close", "classClose.html", "classClose" ],
    [ "Command", "classCommand.html", "classCommand" ],
    [ "Echo", "classEcho.html", "classEcho" ],
    [ "Exit", "classExit.html", "classExit" ],
    [ "Help", "classHelp.html", "classHelp" ],
    [ "Info", "classInfo.html", "classInfo" ],
    [ "Invite", "classInvite.html", "classInvite" ],
    [ "Join", "classJoin.html", "classJoin" ],
    [ "Kick", "classKick.html", "classKick" ],
    [ "List", "classList.html", "classList" ],
    [ "Message", "classMessage.html", "classMessage" ],
    [ "Mode", "classMode.html", "classMode" ],
    [ "Name", "className.html", "className" ],
    [ "Nick", "classNick.html", "classNick" ],
    [ "Notice", "classNotice.html", "classNotice" ],
    [ "Ope", "classOpe.html", "classOpe" ],
    [ "Openhost", "classOpenhost.html", "classOpenhost" ],
    [ "Part", "classPart.html", "classPart" ],
    [ "Ping", "classPing.html", "classPing" ],
    [ "PrivMsg", "classPrivMsg.html", "classPrivMsg" ],
    [ "Quit", "classQuit.html", "classQuit" ],
    [ "Server", "classServer.html", "classServer" ],
    [ "Status", "classStatus.html", "classStatus" ],
    [ "User", "classUser.html", "classUser" ],
    [ "Who", "classWho.html", "classWho" ],
    [ "Whois", "classWhois.html", "classWhois" ]
];