var hierarchy =
[
    [ "Channel", "classChannel.html", null ],
    [ "Client", "classClient.html", null ],
    [ "Command", "classCommand.html", [
      [ "Away", "classAway.html", null ],
      [ "Ban", "classBan.html", null ],
      [ "Close", "classClose.html", null ],
      [ "Echo", "classEcho.html", null ],
      [ "Exit", "classExit.html", null ],
      [ "Help", "classHelp.html", null ],
      [ "Info", "classInfo.html", null ],
      [ "Invite", "classInvite.html", null ],
      [ "Join", "classJoin.html", null ],
      [ "Kick", "classKick.html", null ],
      [ "List", "classList.html", null ],
      [ "Mode", "classMode.html", null ],
      [ "Names", "classNames.html", null ],
      [ "Nick", "classNick.html", null ],
      [ "Notice", "classNotice.html", null ],
      [ "Ope", "classOpe.html", null ],
      [ "Openhost", "classOpenhost.html", null ],
      [ "Part", "classPart.html", null ],
      [ "Pass", "classPass.html", null ],
      [ "Ping", "classPing.html", null ],
      [ "PrivMsg", "classPrivMsg.html", null ],
      [ "Quit", "classQuit.html", null ],
      [ "Status", "classStatus.html", null ],
      [ "User", "classUser.html", null ],
      [ "Who", "classWho.html", null ],
      [ "Whois", "classWhois.html", null ]
    ] ],
    [ "Message", "classMessage.html", null ],
    [ "Server", "classServer.html", null ]
];